law_keywords = {
    "Arbitration": ["arbitrator", "panel", "binding decision", "dispute resolution", "mediation"],
    "Aviation Law": ["air travel", "International Civil Aviation Organization", "aircraft", "aviation regulation", "Air Navigation and Transport Act"],
    "Banking and Finance Law": ["loan transactions", "financial regulation", "bank loans", "financing arrangements", "commercial finance"],
    "Clinical Negligence Law": ["medical negligence", "malpractice", "patient injury", "wrongful treatment", "medical litigation"],
    "European Law": ["European Union", "free movement", "competition law", "EU regulations", "market competition"],
    "Competition Law": ["anti-competitive", "market share", "monopoly", "unfair competition", "regulation"],
    "Construction Law": ["building construction", "engineering", "construction contract", "planning law", "defective construction"],
    "Corporate Law": ["company law", "shareholders", "directors", "Companies Act", "corporate governance"],
    "Criminal Law": ["crime", "punishment", "actus reus", "mens rea", "criminal statute"],
    "Dispute Resolution": ["litigation", "arbitration", "mediation", "conciliation", "negotiation"],
    "Employment Law": ["employer", "employee", "employment rights", "labor law", "workplace"],
    "Energy and Infrastructure Law": ["energy sector", "infrastructure projects", "commercial transactions", "project finance", "regulation"],
    "Environmental Law": ["environmental regulation", "pollution", "sustainable development", "treaties", "natural resources"],
    "Family Law": ["marriage", "divorce", "child custody", "domestic relations", "family court"],
    "Gaming Law": ["gambling", "regulatory compliance", "gaming industry", "criminal law", "competition law"],
    "Human Rights Law": ["human rights", "European Convention on Human Rights", "United Nations", "fundamental rights", "abuse prevention"],
    "Immigration Law": ["immigration policy", "deportation", "citizenship", "visa", "immigration court"],
    "Insolvency Law": ["bankruptcy", "creditors", "debt recovery", "company administration", "insolvency practitioner"],
    "Insurance Law": ["insurance policy", "claims", "contract law", "regulation", "litigation"],
    "Intellectual Property Law": ["trademarks", "patents", "copyright", "intellectual property rights", "registration"],
    "Media Law": ["telecommunications", "broadcasting", "defamation", "censorship", "information technology"],
    "Property Law": ["real property", "leasehold", "tenancy", "property rights", "land transactions"],
    "Public Sector and Local Government Law": ["public law", "constitutional law", "administrative law", "tax law", "judicial review"],
    "Shipping and Maritime Law": ["carriage of goods", "maritime", "ship construction", "insurance", "admiralty"],
    "Sports Law": ["sports contracts", "regulatory compliance", "intellectual property", "negligence", "sports industry"],
    "Tax Law": ["tax regulation", "tax compliance", "tax planning", "revenue", "legislation"],
    "Tort Law": ["damages", "negligence", "civil wrong", "personal injury", "liability"],
    "Wills, Trust and Probate Law": ["estate planning", "will", "trust", "probate", "beneficiaries"],
}